---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: gpupgrade_src
  type: git
  source:
    uri: {{gpupgrade-git-remote}}
    branch: {{gpupgrade-git-branch}}

- name: gpdb_src
  type: git
  source:
    uri: https://github.com/greenplum-db/gpdb
    branch: master

- name: slack-alert
  type: slack-notification
  source:
    url: {{cm_webhook_url}}

- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{gpdb-stable-builds-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: release_candidates/bin_gpdb_centos6/gpdb6/debug/bin_gpdb.tar.gz


jobs:
- name: unit-tests
  plan:
  - get: gpupgrade_src
    trigger: true
  - task: unit-tests
    file: gpupgrade_src/ci/tasks/unit-tests.yml
    on_failure:
      do:
      - *slack_alert

- name: integration-tests
  plan:
  - aggregate:
    - get: gpupgrade_src
      trigger: true
    - get: gpdb_src
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
  - task: integration-tests
    file: gpupgrade_src/ci/tasks/integration-tests.yml
    on_failure:
      do:
      - *slack_alert


slack_alert_anchor: &slack_alert
  put: slack-alert
  params:
    text: |
      Hey team, <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|gpupgrade/$BUILD_JOB_NAME> failed.
